apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookcatalog-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookcatalog
  template:
    metadata:
      labels:
        app: bookcatalog
    spec:
      containers: 
      - name: bookcatalog
        image: $CONTAINER_REGISTRY/bookcatalog:$VERSION
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001  
        env:
        - name: DATABASE_URL 
          value: "postgresql://task9d_user:BWr1yOXHAePNSipQyz17cHcsfSsWXn8m@dpg-cs31k768ii6s738e3a3g-a.oregon-postgres.render.com/task9d"
---
apiVersion: v1
kind: Service
metadata:
  name: bookcatalog-service
spec:
  selector:
    app: bookcatalog
  ports:
    - protocol: TCP
      port: 3001  
      targetPort: 3001 
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventorymanage-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventorymanage
  template:
    metadata:
      labels:
        app: inventorymanage
    spec:
      containers:
      - name: inventorymanage
        image: $CONTAINER_REGISTRY/inventorymanage:$VERSION
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002  
        env:
        - name: DATABASE_URL
          value: "postgresql://task9d_user:BWr1yOXHAePNSipQyz17cHcsfSsWXn8m@dpg-cs31k768ii6s738e3a3g-a.oregon-postgres.render.com/task9d"
---
apiVersion: v1
kind: Service
metadata:
  name: inventorymanage-service
spec:
  selector:
    app: inventorymanage
  ports:
  - protocol: TCP
    port: 3002  
    targetPort: 3002  
  type: LoadBalancer
